import { Prisma, PrismaClient } from "@prisma/client";
const prisma = new PrismaClient();

export async function executeUserSeed() {
  await prisma.user.deleteMany({});

  const roleAdmin = await prisma.role.findFirstOrThrow({
    where: { name: "Admin" },
  });

  const roleMaintenanceTechnician = await prisma.role.findFirstOrThrow({
    where: { name: "Mainentance Technician" },
  });

  const rolePassenger = await prisma.role.findFirstOrThrow({
    where: { name: "Passenger" },
  });

  const roleTrainOperator = await prisma.role.findFirstOrThrow({
    where: { name: "Train Operator" },
  });

  const roleTicketBoothAttendant = await prisma.role.findFirstOrThrow({
    where: { name: "Ticket Booth Attendant" },
  });

  await prisma.user.createMany({
    data: [
      {
        username: "admin1",
        password: "password1",
        roleId: roleAdmin.id,
        phone: "1234567890",
        email: "admin1@example.com",
        address: "Address 1",
        street: "Street 1",
        city: "City 1",
        country: "Country 1",
        postal_code: "12345",
        state: "State 1",
        date_of_birth: new Date("1980-01-01"),
        gender: "Male",
        nationality: "Nationality 1",
        language: "Language 1",
      },
      {
        username: "admin2",
        password: "password2",
        roleId: roleAdmin.id,
        phone: "1234567891",
        email: "admin2@example.com",
        address: "Address 2",
        street: "Street 2",
        city: "City 2",
        country: "Country 2",
        postal_code: "12346",
        state: "State 2",
        date_of_birth: new Date("1981-01-01"),
        gender: "Female",
        nationality: "Nationality 2",
        language: "Language 2",
      },
      // Passengers
      {
        username: "passenger1",
        password: "password3",
        roleId: rolePassenger.id,
        phone: "1234567892",
        email: "passenger1@example.com",
        address: "Address 3",
        street: "Street 3",
        city: "City 3",
        country: "Country 3",
        postal_code: "12347",
        state: "State 3",
        date_of_birth: new Date("1982-01-01"),
        gender: "Male",
        nationality: "Nationality 3",
        language: "Language 3",
      },
      {
        username: "passenger2",
        password: "password4",
        roleId: rolePassenger.id,
        phone: "1234567893",
        email: "passenger2@example.com",
        address: "Address 4",
        street: "Street 4",
        city: "City 4",
        country: "Country 4",
        postal_code: "12348",
        state: "State 4",
        date_of_birth: new Date("1983-01-01"),
        gender: "Female",
        nationality: "Nationality 4",
        language: "Language 4",
      },
      {
        username: "passenger3",
        password: "password5",
        roleId: rolePassenger.id,
        phone: "1234567894",
        email: "passenger3@example.com",
        address: "Address 5",
        street: "Street 5",
        city: "City 5",
        country: "Country 5",
        postal_code: "12349",
        state: "State 5",
        date_of_birth: new Date("1984-01-01"),
        gender: "Male",
        nationality: "Nationality 5",
        language: "Language 5",
      },
      {
        username: "passenger4",
        password: "password6",
        roleId: rolePassenger.id,
        phone: "1234567895",
        email: "passenger4@example.com",
        address: "Address 6",
        street: "Street 6",
        city: "City 6",
        country: "Country 6",
        postal_code: "12350",
        state: "State 6",
        date_of_birth: new Date("1985-01-01"),
        gender: "Female",
        nationality: "Nationality 6",
        language: "Language 6",
      },
      {
        username: "passenger5",
        password: "password7",
        roleId: rolePassenger.id,
        phone: "1234567896",
        email: "passenger5@example.com",
        address: "Address 7",
        street: "Street 7",
        city: "City 7",
        country: "Country 7",
        postal_code: "12351",
        state: "State 7",
        date_of_birth: new Date("1986-01-01"),
        gender: "Male",
        nationality: "Nationality 7",
        language: "Language 7",
      },
      {
        username: "passenger6",
        password: "password8",
        roleId: rolePassenger.id,
        phone: "1234567897",
        email: "passenger6@example.com",
        address: "Address 8",
        street: "Street 8",
        city: "City 8",
        country: "Country 8",
        postal_code: "12352",
        state: "State 8",
        date_of_birth: new Date("1987-01-01"),
        gender: "Female",
        nationality: "Nationality 8",
        language: "Language 8",
      },
      {
        username: "passenger7",
        password: "password9",
        roleId: rolePassenger.id,
        phone: "1234567898",
        email: "passenger7@example.com",
        address: "Address 9",
        street: "Street 9",
        city: "City 9",
        country: "Country 9",
        postal_code: "12353",
        state: "State 9",
        date_of_birth: new Date("1988-01-01"),
        gender: "Male",
        nationality: "Nationality 9",
        language: "Language 9",
      },
      {
        username: "passenger8",
        password: "password10",
        roleId: rolePassenger.id,
        phone: "1234567899",
        email: "passenger8@example.com",
        address: "Address 10",
        street: "Street 10",
        city: "City 10",
        country: "Country 10",
        postal_code: "12354",
        state: "State 10",
        date_of_birth: new Date("1989-01-01"),
        gender: "Female",
        nationality: "Nationality 10",
        language: "Language 10",
      },
      // Train Operators
      {
        username: "trainoperator1",
        password: "password11",
        roleId: roleTrainOperator.id,
        phone: "2234567890",
        email: "trainoperator1@example.com",
        address: "Address 11",
        street: "Street 11",
        city: "City 11",
        country: "Country 11",
        postal_code: "22345",
        state: "State 11",
        date_of_birth: new Date("1970-01-01"),
        gender: "Male",
        nationality: "Nationality 11",
        language: "Language 11",
      },
      {
        username: "trainoperator2",
        password: "password12",
        roleId: roleTrainOperator.id,
        phone: "2234567891",
        email: "trainoperator2@example.com",
        address: "Address 12",
        street: "Street 12",
        city: "City 12",
        country: "Country 12",
        postal_code: "22346",
        state: "State 12",
        date_of_birth: new Date("1971-01-01"),
        gender: "Female",
        nationality: "Nationality 12",
        language: "Language 12",
      },
      {
        username: "trainoperator3",
        password: "password13",
        roleId: roleTrainOperator.id,
        phone: "2234567892",
        email: "trainoperator3@example.com",
        address: "Address 13",
        street: "Street 13",
        city: "City 13",
        country: "Country 13",
        postal_code: "22347",
        state: "State 13",
        date_of_birth: new Date("1972-01-01"),
        gender: "Male",
        nationality: "Nationality 13",
        language: "Language 13",
      },
      {
        username: "trainoperator4",
        password: "password14",
        roleId: roleTrainOperator.id,
        phone: "2234567893",
        email: "trainoperator4@example.com",
        address: "Address 14",
        street: "Street 14",
        city: "City 14",
        country: "Country 14",
        postal_code: "22348",
        state: "State 14",
        date_of_birth: new Date("1973-01-01"),
        gender: "Female",
        nationality: "Nationality 14",
        language: "Language 14",
      },
      {
        username: "trainoperator5",
        password: "password15",
        roleId: roleTrainOperator.id,
        phone: "2234567894",
        email: "trainoperator5@example.com",
        address: "Address 15",
        street: "Street 15",
        city: "City 15",
        country: "Country 15",
        postal_code: "22349",
        state: "State 15",
        date_of_birth: new Date("1974-01-01"),
        gender: "Male",
        nationality: "Nationality 15",
        language: "Language 15",
      },
      // Ticket Booth Attendants
      {
        username: "attendant1",
        password: "password16",
        roleId: roleTicketBoothAttendant.id,
        phone: "3234567890",
        email: "attendant1@example.com",
        address: "Address 16",
        street: "Street 16",
        city: "City 16",
        country: "Country 16",
        postal_code: "32345",
        state: "State 16",
        date_of_birth: new Date("1960-01-01"),
        gender: "Male",
        nationality: "Nationality 16",
        language: "Language 16",
      },
      {
        username: "attendant2",
        password: "password17",
        roleId: roleTicketBoothAttendant.id,
        phone: "3234567891",
        email: "attendant2@example.com",
        address: "Address 17",
        street: "Street 17",
        city: "City 17",
        country: "Country 17",
        postal_code: "32346",
        state: "State 17",
        date_of_birth: new Date("1961-01-01"),
        gender: "Female",
        nationality: "Nationality 17",
        language: "Language 17",
      },
      {
        username: "attendant3",
        password: "password18",
        roleId: roleTicketBoothAttendant.id,
        phone: "3234567892",
        email: "attendant3@example.com",
        address: "Address 18",
        street: "Street 18",
        city: "City 18",
        country: "Country 18",
        postal_code: "32347",
        state: "State 18",
        date_of_birth: new Date("1962-01-01"),
        gender: "Male",
        nationality: "Nationality 18",
        language: "Language 18",
      },
      {
        username: "attendant4",
        password: "password19",
        roleId: roleTicketBoothAttendant.id,
        phone: "3234567893",
        email: "attendant4@example.com",
        address: "Address 19",
        street: "Street 19",
        city: "City 19",
        country: "Country 19",
        postal_code: "32348",
        state: "State 19",
        date_of_birth: new Date("1963-01-01"),
        gender: "Female",
        nationality: "Nationality 19",
        language: "Language 19",
      },
      {
        username: "attendant5",
        password: "password20",
        roleId: roleTicketBoothAttendant.id,
        phone: "3234567894",
        email: "attendant5@example.com",
        address: "Address 20",
        street: "Street 20",
        city: "City 20",
        country: "Country 20",
        postal_code: "32349",
        state: "State 20",
        date_of_birth: new Date("1964-01-01"),
        gender: "Male",
        nationality: "Nationality 20",
        language: "Language 20",
      },
      // Maintenance Technicians
      {
        username: "technician1",
        password: "password21",
        roleId: roleMaintenanceTechnician.id,
        phone: "4234567890",
        email: "technician1@example.com",
        address: "Address 21",
        street: "Street 21",
        city: "City 21",
        country: "Country 21",
        postal_code: "42345",
        state: "State 21",
        date_of_birth: new Date("1950-01-01"),
        gender: "Male",
        nationality: "Nationality 21",
        language: "Language 21",
      },
      {
        username: "technician2",
        password: "password22",
        roleId: roleMaintenanceTechnician.id,
        phone: "4234567891",
        email: "technician2@example.com",
        address: "Address 22",
        street: "Street 22",
        city: "City 22",
        country: "Country 22",
        postal_code: "42346",
        state: "State 22",
        date_of_birth: new Date("1951-01-01"),
        gender: "Female",
        nationality: "Nationality 22",
        language: "Language 22",
      },
      {
        username: "technician3",
        password: "password23",
        roleId: roleMaintenanceTechnician.id,
        phone: "4234567892",
        email: "technician3@example.com",
        address: "Address 23",
        street: "Street 23",
        city: "City 23",
        country: "Country 23",
        postal_code: "42347",
        state: "State 23",
        date_of_birth: new Date("1952-01-01"),
        gender: "Male",
        nationality: "Nationality 23",
        language: "Language 23",
      },
      {
        username: "technician4",
        password: "password24",
        roleId: roleMaintenanceTechnician.id,
        phone: "4234567893",
        email: "technician4@example.com",
        address: "Address 24",
        street: "Street 24",
        city: "City 24",
        country: "Country 24",
        postal_code: "42348",
        state: "State 24",
        date_of_birth: new Date("1953-01-01"),
        gender: "Female",
        nationality: "Nationality 24",
        language: "Language 24",
      },
      {
        username: "technician5",
        password: "password25",
        roleId: roleMaintenanceTechnician.id,
        phone: "4234567894",
        email: "technician5@example.com",
        address: "Address 25",
        street: "Street 25",
        city: "City 25",
        country: "Country 25",
        postal_code: "42349",
        state: "State 25",
        date_of_birth: new Date("1954-01-01"),
        gender: "Male",
        nationality: "Nationality 25",
        language: "Language 25",
      },
      {
        username: "technician6",
        password: "password26",
        roleId: roleMaintenanceTechnician.id,
        phone: "4234567895",
        email: "technician6@example.com",
        address: "Address 26",
        street: "Street 26",
        city: "City 26",
        country: "Country 26",
        postal_code: "42350",
        state: "State 26",
        date_of_birth: new Date("1955-01-01"),
        gender: "Female",
        nationality: "Nationality 26",
        language: "Language 26",
      },
      {
        username: "technician7",
        password: "password27",
        roleId: roleMaintenanceTechnician.id,
        phone: "4234567896",
        email: "technician7@example.com",
        address: "Address 27",
        street: "Street 27",
        city: "City 27",
        country: "Country 27",
        postal_code: "42351",
        state: "State 27",
        date_of_birth: new Date("1956-01-01"),
        gender: "Male",
        nationality: "Nationality 27",
        language: "Language 27",
      },
      {
        username: "technician8",
        password: "password28",
        roleId: roleMaintenanceTechnician.id,
        phone: "4234567897",
        email: "technician8@example.com",
        address: "Address 28",
        street: "Street 28",
        city: "City 28",
        country: "Country 28",
        postal_code: "42352",
        state: "State 28",
        date_of_birth: new Date("1957-01-01"),
        gender: "Female",
        nationality: "Nationality 28",
        language: "Language 28",
      },
      {
        username: "technician9",
        password: "password29",
        roleId: roleMaintenanceTechnician.id,
        phone: "4234567898",
        email: "technician9@example.com",
        address: "Address 29",
        street: "Street 29",
        city: "City 29",
        country: "Country 29",
        postal_code: "42353",
        state: "State 29",
        date_of_birth: new Date("1958-01-01"),
        gender: "Male",
        nationality: "Nationality 29",
        language: "Language 29",
      },
      {
        username: "technician10",
        password: "password30",
        roleId: roleMaintenanceTechnician.id,
        phone: "4234567899",
        email: "technician10@example.com",
        address: "Address 30",
        street: "Street 30",
        city: "City 30",
        country: "Country 30",
        postal_code: "42354",
        state: "State 30",
        date_of_birth: new Date("1959-01-01"),
        gender: "Female",
        nationality: "Nationality 30",
        language: "Language 30",
      },
    ],
  });
}
