name: protect-migrations

on:
  pull_request:
    branches:
      - "feature/protect-migrations"
    paths:
      - "prisma/migrations/**"

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Fetch all branches
        run: git fetch origin +refs/heads/*:refs/remotes/origin/*

      - name: Check for deleted migration files
        run: |
          BASE_SHA=$(git rev-parse origin/${{ github.event.pull_request.base.ref }})
          HEAD_SHA=$(git rev-parse HEAD)
          git diff --name-status $BASE_SHA $HEAD_SHA | grep "^D" | grep "prisma/migrations/"
        continue-on-error: true
        id: check_deleted_migrations

      - name: Fail if migrations are deleted
        if: steps.check_deleted_migrations.outcome == 'success'
        run: |
          echo "Migration files have been deleted, which is not allowed."
          exit 1
